### PR TITLE
getUnclaimedMarketCreatorFees

### PR DESCRIPTION
**Pull request by epheph**

### CODE REVIEW

**Comment by epheph** [comment]
@adrake33 i finally wrote this thing you asked for. Could i get some help on the jsdoc format for an object return with dynamic keys (marketIDs?)

**Comment by adrake33** [comment]
Does it make sense to return it as an object?  It seems like technically it should be an array if it's keyed by marketIDs.  If it should be an object, I think you could do something like: 

```@returns {Object.<string, number>}```

**Comment by epheph** [comment]
@adrake33 perhaps it does, it would be more like how getMarketsInfo works.

@stephensprinkle do you have a preference?

```
{
        "0x0000000000000000000000000000000000000001": 0,
        "0x0000000000000000000000000000000000000002": 0,
      }
```
vs
```
[{
        marketID: "0x0000000000000000000000000000000000000001",
        unclaimedFee: 0
},{
        marketID: "0x0000000000000000000000000000000000000002",
        unclaimedFee: 0
      }
]
```

**Comment by stephensprinkle** [comment]
Pref would be 1st for me.

**Comment by epheph** [comment]
@stephensprinkle alright, that's how it's already written!

**Comment by epheph** [comment]
Updated jsdoc

**Comment by adrake33** [comment]
@epheph It looks like Sprinkle edited his original comment. Can you please update it to be an array?

**Comment by epheph** [comment]
https://github.com/AugurProject/augur-node/pull/160/files

**Pull request merged**
