### PR TITLE
Trade simulation should adjust display prices for numTicks

### PR DESCRIPTION
**Pull request by tinybike**
Story details: https://app.clubhouse.io/augur/story/11511

### CODE REVIEW

**Comment by tinybike** [comment]
@nuevoalex Fixed a couple other inconsistencies; PR should be good to go now.

**Comment by nuevoalex** [comment]
This can be closed now that we're fixing numTicks for cat 3,6,7 I think

**Comment by tinybike** [comment]
Crud, I mixed in another update to this PR to simulateTrade, making it so it updates shareBalances for share increases as well as decreases.  Let me update the PR so it just has those shareBalance changes.

**Comment by tinybike** [comment]
Ah right, resolving that now

**Comment by tinybike** [comment]
Ok, should be good to go Alex if you want to give it a once-over!

**Comment by tinybike** [comment]
I guess there's no reason for an additional once-over; merging now.

**Pull request merged**
