### PR TITLE
switching getMarketPriceHistory to use chunked logs

### PR DESCRIPTION
**Pull request by kevinday**
Not quite ready to be merged, but PR-ing for review.

A few tests are failing, but seems to be a problem with get-chunked-logs and not these changes specifically.
`rpcInterface.getCurrentBlock()` is returning null here when the tests get unhappy about when trying to call `number` on:
https://github.com/AugurProject/augur.js/blob/master/src/logs/get-logs-chunked.js#L20

Do you know why this cull would be returning null?

### CODE REVIEW

**Comment by tinybike** [comment]
Hm, no I don't -- is `rpcInterface.getCurrentBlock()` returning `null` for you in actual use, or just in the tests?  (If just in the tests, did you include that in your mock?)

**Comment by kevinday** [comment]
AFK for a bit but I will double check later.

**Comment by kevinday** [comment]
The issue was that I wasn't mocking that call. John showed me how to do that and the getMarketPriceHistory are now passing again. Hmm, Travis is showing a createBranch test failing which I didn't touch, and all tests pass locally for me 🤔

**Comment by kevinday** [comment]
@tinybike looks like tests are passing now. Can you review this when you get a chance?

**Comment by tinybike** [comment]
Looks good, thanks!

**Pull request merged**
