### PR TITLE
Changes to support recent ethrpc updates.

### PR DESCRIPTION
**Pull request by MicahZoltu**
The primary change here is an explicit check for support of subscriptions with ethrpc rather than insinuating subscription support via IPC/WS support.

### CODE REVIEW

**Comment by tinybike** [comment]
I npm linked augur.js with the updated ethereumjs-connect and ethrpc locally and tried to run `npm test`, which gave the following errors:
```
  1) connect.connect Should handle a missing rpcinfo async:
     TypeError: Cannot read property 'unsubscribe' of undefined
      at src/modules/connect.js:196:20
      at Object.connect (test/unit/core/connect.js:821:11)
      at Object.connect (src/modules/connect.js:194:15)
      at Context.<anonymous> (test/unit/core/connect.js:798:25)

  2) connect.connect Should handle a rpcinfo string async:
     TypeError: Cannot read property 'unsubscribe' of undefined
      at src/modules/connect.js:196:20
      at Object.connect (test/unit/core/connect.js:858:11)
      at Object.connect (src/modules/connect.js:194:15)
      at Context.<anonymous> (test/unit/core/connect.js:798:25)

  3) connect.connect Should handle a rpcinfo as an object async:
     TypeError: Cannot read property 'unsubscribe' of undefined
      at src/modules/connect.js:196:20
      at Object.connect (test/unit/core/connect.js:901:11)
      at Object.connect (src/modules/connect.js:194:15)
      at Context.<anonymous> (test/unit/core/connect.js:798:25)

  4) connect.connect Should handle a rpcinfo as an object with an augurNodes property async:
     TypeError: Cannot read property 'unsubscribe' of undefined
      at src/modules/connect.js:196:20
      at Object.connect (test/unit/core/connect.js:954:11)
      at Object.connect (src/modules/connect.js:194:15)
      at Context.<anonymous> (test/unit/core/connect.js:798:25)

  5) connect.connect Should handle a rpcinfo as a function async:
     TypeError: Cannot read property 'unsubscribe' of undefined
      at src/modules/connect.js:196:20
      at Object.connect (test/unit/core/connect.js:997:11)
      at Object.connect (src/modules/connect.js:194:15)
      at Context.<anonymous> (test/unit/core/connect.js:792:25)

  6) pacemaker {"cb":{},"rpc":{"wsURL":"somewsURL","ipcpath":"someipcpath","subscriptions":{}},"filter":{"block":{"id":"0xb1","heartbeat":null},"contracts":{"id":"0xc1","heartbeat":null},"testEvent":{"id":"0xe1","heartbeat":null}}}:
     TypeError: augur.rpc.getFilterChanges is not a function
      at Object.poll_filter (src/filters.js:251:19)
      at src/filters.js:375:18
      at Object.async.forEachOf.async.eachOf (node_modules/async/lib/async.js:233:13)
      at Object.pacemaker (src/filters.js:373:15)
      at Context.<anonymous> (test/unit/core/filters.js:1547:21)

  7) pacemaker {"cb":{},"rpc":{"wsURL":"somewsURL","ipcpath":"someipcpath","subscriptions":{}},"filter":{"block":{"id":"0xb1","heartbeat":null},"contracts":{"id":"0xc1","heartbeat":null},"testEvent":{"id":"0xe1","heartbeat":null}}}:
     TypeError: augur.rpc.getFilterChanges is not a function
      at Object.poll_filter (src/filters.js:251:19)
      at src/filters.js:375:18
      at Object.async.forEachOf.async.eachOf (node_modules/async/lib/async.js:233:13)
      at Object.pacemaker (src/filters.js:373:15)
      at Context.<anonymous> (test/unit/core/filters.js:1547:21)

  8) pacemaker {"cb":{},"rpc":{"wsURL":"somewsURL","ipcpath":"someipcpath","subscriptions":{}},"filter":{"block":{"id":"0xb1","heartbeat":null},"contracts":{"id":"0xc1","heartbeat":null},"testEvent":{"id":"0xe1","heartbeat":null}}}:
     TypeError: augur.rpc.getFilterChanges is not a function
      at Object.poll_filter (src/filters.js:251:19)
      at src/filters.js:375:18
      at Object.async.forEachOf.async.eachOf (node_modules/async/lib/async.js:233:13)
      at Object.pacemaker (src/filters.js:373:15)
      at Context.<anonymous> (test/unit/core/filters.js:1547:21)
```
```
  1) getTradingActions sell actions bid with same shares and prices, no position:

      AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
      + expected - actual

           "avgPrice": "0.41152"
           "costEth": "-2.0576"
           "feeEth": "0.0576"
           "feePercent": "2.7993779160186625"
      -    "gasEth": "0"
      +    "gasEth": "0.02119592"
           "noFeePrice": "0.42304"
           "shares": "5"
         }
       ]
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at Object.assertions (test/unit/trading/tradingActions.js:1676:16)
      at Context.<anonymous> (test/unit/trading/tradingActions.js:888:16)

  2) getTradingActions sell actions bid with less amount and same price, no position:

      AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
      + expected - actual

           "avgPrice": "0.41152"
           "costEth": "-0.82304"
           "feeEth": "0.02304"
           "feePercent": "2.7993779160186625"
      -    "gasEth": "0"
      +    "gasEth": "0.02119592"
           "noFeePrice": "0.42304"
           "shares": "2"
         }
         {
           "avgPrice": "1.00576"
           "costEth": "-3.01728"
           "feeEth": "0.01728"
           "feePercent": "0.96"
      -    "gasEth": "0"
      +    "gasEth": "0.02791268"
           "noFeePrice": "0.6"
           "shares": "3"
         }
       ]
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at Object.assertions (test/unit/trading/tradingActions.js:1835:16)
      at Context.<anonymous> (test/unit/trading/tradingActions.js:888:16)

  3) getTradingActions sell actions bids with same shares and higher prices, no position:

      AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
      + expected - actual

           "avgPrice": "0.18904"
           "costEth": "-0.9452"
           "feeEth": "0.0452"
           "feePercent": "4.7820567075751163"
      -    "gasEth": "0"
      +    "gasEth": "0.02119592"
           "noFeePrice": "0.19808"
           "shares": "5"
         }
       ]
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at Object.assertions (test/unit/trading/tradingActions.js:2041:16)
      at Context.<anonymous> (test/unit/trading/tradingActions.js:888:16)

  4) getTradingActions sell actions bid with same shares and price, smaller position:

      AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
      + expected - actual

           "avgPrice": "0.58848"
           "costEth": "1.17696"
           "feeEth": "0.02304"
           "feePercent": "1.9575856443719412"
      -    "gasEth": "0"
      +    "gasEth": "0.01574842"
           "noFeePrice": "0.6"
           "shares": "2"
         }
         {
           "avgPrice": "0.41152"
           "costEth": "-1.23456"
           "feeEth": "0.03456"
           "feePercent": "2.7993779160186625"
      -    "gasEth": "0"
      +    "gasEth": "0.02119592"
           "noFeePrice": "0.42304"
           "shares": "3"
         }
       ]
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at Object.assertions (test/unit/trading/tradingActions.js:2178:16)
      at Context.<anonymous> (test/unit/trading/tradingActions.js:888:16)

  5) getTradingActions sell actions bid with same shares and higher price, smaller position:

      AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
      + expected - actual

           "avgPrice": "0.68824"
           "costEth": "1.37648"
           "feeEth": "0.02352"
           "feePercent": "1.7087062652563059"
      -    "gasEth": "0"
      +    "gasEth": "0.01574842"
           "noFeePrice": "0.7"
           "shares": "2"
         }
         {
           "avgPrice": "0.31176"
           "costEth": "-0.93528"
           "feeEth": "0.03528"
           "feePercent": "3.7721324095458044"
      -    "gasEth": "0"
      +    "gasEth": "0.02119592"
           "noFeePrice": "0.32352"
           "shares": "3"
         }
       ]
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at Object.assertions (test/unit/trading/tradingActions.js:2278:16)
      at Context.<anonymous> (test/unit/trading/tradingActions.js:888:16)
```

**Comment by tinybike** [comment]
Also, `env.js` no longer works.  The way this is supposed to work is, bring up a Node console (in the augur.js directory) and type:
```javascript
require('./env')
```
and it dumps you into a fully-configured environment.  With the changes, I get the following error:
```
TypeError: augur.rpc.setLocalNode is not a function
    at Object.setup (/home/jack/src/augur.js/test/tools.js:606:32)
    at global.augur.global.reload (/home/jack/src/augur.js/env.js:19:16)
    at Object.<anonymous> (/home/jack/src/augur.js/env.js:20:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by tinybike** [comment]
`scripts/canned-markets.js` now throws the following error when I try to run it:
```
/home/jack/src/augur.js/scripts/canned-markets.js:581
    console.debug("setCash success:", r.callReturn);
            ^

TypeError: console.debug is not a function
    at Object.onSuccess (/home/jack/src/augur.js/scripts/canned-markets.js:581:13)
    at /home/jack/src/ethrpc/index.js:1440:18
    at Object.parse (/home/jack/src/ethrpc/index.js:488:16)
    at Object.<anonymous> (/home/jack/src/ethrpc/index.js:270:12)
    at Object.blockchainMessageHandler (/home/jack/src/ethrpc/index.js:284:7)
    at Object.<anonymous> (/home/jack/src/ethrpc/index.js:185:56)
    at WsTransport.<anonymous> (/home/jack/src/ethrpc/transport/ws-transport.js:25:5)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/jack/src/ethrpc/node_modules/yaeti/lib/EventTarget.js:117:12)
    at W3CWebSocket.onMessage (/home/jack/src/ethrpc/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/jack/src/ethrpc/node_modules/websocket/lib/W3CWebSocket.js:205:19)
```

**Comment by tinybike** [comment]
Fixed the canned-markets error in e8878ada62d8de5d773538047da69ec871f757ec

**Comment by MicahZoltu** [comment]
All tests fixed except for the gas ones, see discussion in `ethrpc` PR (related to failing UI tests) for details.  Once again, it appears I didn't run all of the tests after making some tweaks (in this case, subscription support detection stuff).  😢  Yesterday just wasn't my day apparently.

I'll look into the problem with `env.js`.  I didn't realize there was a script that used `ethrpc`.  I suspect the changes will just involve fixing it up to invoke ethrpc correctly (via connect).

**Comment by MicahZoltu** [comment]
I *think* I have `env.js` working, though I'm not sure what the best way to verify is.  The `require` statement completes successfully, I see some output of some stats that look like details about Augur (all suggesting that it is connected and functioning) and I can do `augur.rpc.version()` afterwards and get the correct result.  Let me know what else I can/should do to validate it.

**Comment by MicahZoltu** [comment]
Node, I removed IPC and WS support from `env.js` since all of the calls in it are sync.  ethrpc will throw an exception if you pass it async connection information when doing a synchronous connect (since that doesn't make sense).  I can refactor `env.js` to be fully async, which would allow for setting up IPC and WS connections as well but I wanted to start with the simple solution and let you (@jack) decide whether async support is desirable in this script since I don't really know what the usage scenarios for the script are.

**Pull request merged**
